# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "cudf-sys"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
links = "cudf-sys"

[dependencies]
cxx = { workspace = true }
rmm-sys = { path = "../rmm-sys" }

[build-dependencies]
cc = { version = "1.2", features = ["parallel"] }
cxx-build = { workspace = true }
cmake = { workspace = true, optional = true }

[features]
vendored = ["dep:cmake", "rmm-sys/vendored"]
