# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

[workspace]
members = ["rmm-sys", "cudf-sys", "cudf"]
resolver = "3"

[workspace.package]
version = "0.0.0+26.04.00"
edition = "2024"
rust-version = "1.85"
license = "Apache-2.0"
repository = "https://github.com/rapidsai/cudf"

[workspace.dependencies]
cxx = "1.0"
cxx-build = "1.0"
