# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "rmm-sys"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
links = "rmm-sys"

[dependencies]
cxx = { workspace = true }

[build-dependencies]
cxx-build = { workspace = true }
