# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "cudf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cudf-sys = { path = "../cudf-sys" }
rmm = { path = "../rmm" }
cxx = { workspace = true }
arrow-array = { version = "56", optional = true }
arrow-buffer = { version = "56", optional = true }
arrow-data = { version = "56", optional = true }
arrow-schema = { version = "56", optional = true }

[features]
vendored = ["cudf-sys/vendored"]
arrow = ["dep:arrow-array", "dep:arrow-buffer", "dep:arrow-data", "dep:arrow-schema"]

[[bench]]
name = "gpu_ops"
harness = false

[dev-dependencies]
criterion.workspace = true
