# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "cudf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cudf-sys = { path = "../cudf-sys" }
rmm-sys = { path = "../rmm-sys" }
cxx = { workspace = true }

[features]
vendored = ["cudf-sys/vendored"]
